# serverless.yml

plugins:
  - serverless-plugin-typescript
  - serverless-functions-base-path

service: wardrobe-gql

provider:
  name: aws
  runtime: nodejs12.x

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: lambdaServer.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

custom:
  functionsBasePath: src/server
